# Generated by Django 3.0.6 on 2020-07-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=14)),
                ('dob', models.DateTimeField()),
                ('district', models.CharField(max_length=50)),
                ('province', models.CharField(default='', max_length=50)),
                ('desc', models.TextField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=196)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('i_id', models.AutoField(primary_key=True, serialize=False)),
                ('picture1', models.ImageField(upload_to='palmpic')),
                ('picture2', models.ImageField(upload_to='palmpic')),
                ('dob', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
