# Generated by Django 3.0.6 on 2020-07-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='dob',
            field=models.DateTimeField(blank=True, default=''),
        ),
    ]
