# Generated by Django 3.0.6 on 2020-07-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pweb', '0008_auto_20200710_1026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Client0',
        ),
    ]
