# Generated by Django 3.0.6 on 2020-07-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pweb', '0011_auto_20200710_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dob',
            field=models.DateField(blank=True),
        ),
    ]
