# Generated by Django 3.0.6 on 2020-07-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pweb', '0013_auto_20200710_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
