# Generated by Django 3.0.6 on 2020-07-10 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pweb', '0015_auto_20200710_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='dob',
            new_name='dou1',
        ),
    ]
