# Generated by Django 3.0.6 on 2020-07-10 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pweb', '0016_auto_20200710_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
