# Generated by Django 3.0.6 on 2020-07-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pweb', '0017_client_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='time',
        ),
        migrations.AlterField(
            model_name='client',
            name='dob',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
