# Generated by Django 3.0.6 on 2020-07-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pweb', '0019_auto_20200710_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dob',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='dou1',
            field=models.DateTimeField(),
        ),
    ]
