# Generated by Django 3.0.6 on 2020-07-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pweb', '0020_auto_20200710_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='picture1',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='image',
            name='picture2',
        ),
    ]
