# Generated by Django 3.0.6 on 2020-07-12 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pweb', '0021_auto_20200711_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='picture',
            new_name='picture1',
        ),
    ]
