# Generated by Django 3.0.6 on 2020-07-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pweb', '0022_auto_20200712_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='dou1',
            field=models.DateTimeField(default=''),
        ),
    ]
