# Generated by Django 3.0.6 on 2020-07-12 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pweb', '0023_auto_20200712_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='dou1',
        ),
    ]
