# Generated by Django 3.0.6 on 2020-07-12 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pweb', '0024_remove_image_dou1'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='dou1',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='email',
            field=models.EmailField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='phone',
            field=models.CharField(default='', max_length=14),
        ),
    ]
