# Generated by Django 3.0.6 on 2020-07-13 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pweb', '0026_image_picture2'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='desc',
            field=models.TextField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
