# Generated by Django 3.0.6 on 2020-07-13 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pweb', '0028_auto_20200713_0726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='province',
            new_name='pro',
        ),
    ]
