# Generated by Django 3.0.6 on 2020-07-13 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pweb', '0029_auto_20200713_0729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='desc',
            new_name='desc1',
        ),
    ]
