# Generated by Django 3.0.6 on 2020-07-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pweb', '0031_nav'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nav',
        ),
    ]
