# Generated by Django 3.0.6 on 2020-07-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pweb', '0032_delete_nav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='pro',
        ),
    ]
